openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: This is a sample API to manage a list of tasks.
servers:
  - url: https://dummyjson.com/
paths:
  /todos:
    get:
      summary: Retrieve a list of tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'

  /todos/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: ID of the task
        schema:
          type: integer
    get:
      summary: Retrieve a specific task
      responses:
        '200':
          description: A single task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    put:
      summary: Update a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '200':
          description: Task updated successfully
    delete:
      summary: Delete a task
      responses:
        '204':
          description: Task deleted successfully

  /todos/add:
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '201':
          description: Task created successfully

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        todo:
          type: string
        complited:
          type: boolean
        userId:
          type: integer
    NewTodo:
      type: object
      properties:
        todo:
          type: string
        complited:
          type: boolean
        userId:
          type: integer
